### ISSUE TITLE
Can we unregister the agent at shutdown?

### ISSUE THREAD

**Issue by devamchakrabarty** [bfarr-rh/azure-devops-ocp-agent#7]
When the pod in OpenShift shuts down / crashes / terminates, is there a way to unregister / remove it as an agent from the Azure DevOps Agent Pool? 
The reason I'm asking this question is because we have tried using this approach but over a period of six months it has left a LOT of offline agents in ADO because the pods in OpenShift were spun down / crashed etc.

**Comment by bfarr-rh** [comment]
Perhaps we could try this  - add a PreStop hook and run the command 

/azp/agent/bin/Agent.Listener remove --auth PAT --token $AZP_TOKEN

For example adjusting this command to the deployment or deploymentconfig
oc patch dc wildfly-app -p '{"spec": {"template": {"spec": {"containers": [{"name": "wildfly-app","lifecycle": {"preStop": {"exec": {"command": ["/jboss-cli.sh", "--connect", "command=:shutdown[timeout=10]"]}}}}]}}}}

**Note this issue**
https://github.com/microsoft/azure-pipelines-agent/issues/3001
You MUST select the PAT to be for "All accessible organizations" in order to be used for removing the agent. If your PAT is only for the collection when built, it will only be able to add it to that pool.

**Comment by devamchakrabarty** [comment]
That works. Thanks @bfarr-rh 👍🏽
