### ISSUE TITLE
Override Agent Restart

### ISSUE THREAD

**Issue by devamchakrabarty** [bfarr-rh/azure-devops-ocp-agent#9]
Hi,
As mentioned in point 9 of the [documentation](https://github.com/bfarr-rh/azure-devops-ocp-agent?tab=readme-ov-file#deploying--running-the-agent), the Agent is set to complete with each job and is restarted by OpenShift. This however poses a problem for classic release pipelines. 
When the agent jobs are small and there are multiple stages to deploy into, then as each stage completes OpenShift restarts the pod. After 3 or 4 such restarts, the pods enter into a CrashLoopBackoff in OpenShift, and waits for the configured amount of time before attempting to restart the pod. This means that not only does the release pipeline take a long time to complete as it waits for agents to be available, but sometimes the waiting also times out and fails the pipeline altogether.
Question: What is the best way to solve this problem? There are a few things we are thinking about, but some help would be greatly appreciated. We could theoretically:
1. Prevent the restart when each agent job completes. We are not sure what implications that might have for clean up etc. Maybe we could keep it alive for N jobs before restarting the agent. @bfarr-rh did you get a chance to [dig into it](https://github.com/bfarr-rh/azure-devops-ocp-agent/issues/5#issuecomment-1845371661)?
2. Configure OpenShift to not put the pods into a CrashLoopBackoff state when they restart, maybe some form of graceful restart.
3. Change the pipelines from classic to YAML and combine all stages into a single stage with different jobs

**Comment by mhano** [comment]
FYI - we are trialling a work-around of cycling the agent after the first job finishing 11 minutes after pod start-up.

k8s resets crashloopbackoff tracking at 10 minutes, reverting to an immediate pod restart rather than exponentially backed off delay before re-start.

This is a trade off between minimising the risk of memory/process/disk resource leaks and the microsoft approach of a deployment that triggers a k8s crash-loop-backoff behaviour by exiting with every job. With a number of agents in a pool, an occasional (10 minute) relatively randomly timed immediate restart should have negligible impact on our ADO throughput whilst minimising the risk of resource leaks.

```
/azp/agent/bin/Agent.Listener configure --unattended --agent "${AZP_AGENT_NAME}-${MY_POD_NAME}" \
    --url "$AZP_URL" --auth PAT --token "$AZP_TOKEN" --pool "${AZP_POOL}" \
    --work /_work --replace --acceptTeeEula \
&& \
while [[ $SECONDS -lt 660 ]]; do \
    /azp/agent/externals/node/bin/node /azp/agent/bin/AgentService.js interactive --once; \
    if [[ $? -ne 0 ]]; then exit 1; fi; \
done
```

(newlines / spacing added for readability)

**Comment by bfarr-rh** [comment]
I am not sure of the reason for the Crashback loop - is this associated
with the process not starting ? or container image.

But if we look at option 1 to have a more long running job then we
could consider the maintenance jobs configuration in the pool.
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser
You can configure agent pools to periodically clean stale working
directories and repositories. This should reduce the potential for the
agents to run out of disk space. Maintenance jobs are configured at the
organization level in agent pool settings.

**Comment by mhano** [comment]
The crashloopbackoff is purely because the container is exiting after 1 job (--once) often only shortly after the container starts (seconds to minutes). Keeping it running for at minimum 10+ minutes solves this.

We were not confident enough in the agent's stability / resource management / cleanup to switch it away from --once. Our nervousness was mostly because all the Microsoft docs/samples for containerised deploy include "--once".

**Comment by bfarr-rh** [comment]
Perhaps we should look at keda instead to scale

https://keda.sh/blog/2021-05-27-azure-pipelines-scaler/




Benjamin Farr



[image: image.png]

https://www.redhat.com/en/anz-virtual-events-hub

**Comment by mhano** [comment]
Thanks Ben, definitely worth considering an alternate activation/processing model... with the way agents / agent pools are managed azure/ADO side it could be a bit tricky - I'll have a read through and compare notes with the Microsoft docs and the engineering team.
